# Stage 1: Build Vue app
FROM node:24.3.0 as build-stage
RUN mkdir /home/Portfolio
WORKDIR /home/Portfolio
COPY . .
RUN npm install 
RUN npm run build

# Stage 2: Serve Vue app with Nginx
FROM nginx:1.29.0 as prod-stage
COPY --from=build-stage /home/Portfolio/dist /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]